project:
  type: website
  render:
    - "*.qmd"
    - "arts/*.qmd"
    - "genai/*.qmd"
    - "!data/"

website:
  title: "CCGL9065"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Assessment Items
        menu:
          - href: portfolio_roadmap.qmd#weekly-research-reflection-20
            text: Weekly Reflection
          - href: portfolio_roadmap.qmd#deliverable-1-final-reflective-essay-20
            text: Final Portfolio
      - href: ind.qmd
        text: Portfolios|2024

format:
  html:
    theme: Zephyr
    css: styles.css
    toc: true
    page-layout: full
    include-after-body:
      - text: |
          <!-- Cloudflare Web Analytics --><script defer src='https://static.cloudflareinsights.com/beacon.min.js' data-cf-beacon='{"token": "57d0bc1c02d541369839e257e1819f73"}'></script><!-- End Cloudflare Web Analytics -->

resources:
  - "data/*"



